create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  summary text,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_sync_runs_source_created_at
  on public.sync_runs (source, created_at desc);

create table if not exists public.sync_health (
  source text primary key,
  status text not null,
  summary text,
  metrics jsonb not null default '{}'::jsonb,
  consecutive_upstream_failures integer not null default 0 check (consecutive_upstream_failures >= 0),
  last_attempt_at timestamptz not null default timezone('utc', now()),
  last_success_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now())
);

revoke all on table public.sync_runs from anon, authenticated;
revoke all on table public.sync_health from anon, authenticated;
